BEGIN TRANSACTION;

CREATE TABLE "Albums" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL,
	"Artist"	INTEGER NOT NULL,
	"CoverArt"	BLOB,
	PRIMARY KEY("ID"),
	FOREIGN KEY("Artist") REFERENCES "Artists"("ID")
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

CREATE TABLE "Artists" (
	"ID"	INTEGER NOT NULL UNIQUE,
	"Name"	TEXT NOT NULL UNIQUE,
	"Picture"	BLOB,
	PRIMARY KEY("ID")
);

CREATE TABLE "Tracks" (
	"Checksum"	TEXT NOT NULL UNIQUE,
	"FileLocation"	TEXT NOT NULL UNIQUE,
	"Title"	TEXT NOT NULL,
	"Album"	INTEGER NOT NULL,
	"TrackNum"	INTEGER,
	"TotalTracks"	INTEGER,
	"DiscNum"	INTEGER,
	"TotalDiscs"	INTEGER,
	PRIMARY KEY("Checksum"),
	FOREIGN KEY("Album") REFERENCES "Albums"("ID")
		ON UPDATE CASCADE
		ON DELETE CASCADE
);

COMMIT;